Task 5/WebUI/Controllers/OrderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DAL.Model;
using DAL.UnitOfWork;
using WebUI.Models;

namespace WebUI.Controllers
{
    [Authorize(Roles = Models.RoleName.Read)]
    public class OrderController : BaseCRUD<DAL.Model.Order, Models.Order>
    {
        public OrderController(IUnitOfWork unitOfWork) : base(unitOfWork)
        {
        }

        protected override DAL.Model.Order CreateNewEntity()
        {
            return new DAL.Model.Order
            {
                Customer = new DAL.Model.Customer(),
                Date = DateTime.Now,
                Seller = new DAL.Model.Seller(),
                Product = new DAL.Model.Product(),
                ProductCount = 1,
            };
        }

        protected override int GetId(Models.Order model)
        {
            return model.Id;
        }
    }
}

Task 5/WebUI/Controllers/ProductController.cs
using AutoMapper;
using DAL.Model;
using DAL.Repository;
using DAL.UnitOfWork;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebUI.Models;

namespace WebUI.Controllers
{
    [Authorize(Roles = Models.RoleName.Read)]
    public class ProductController : BaseCRUD<DAL.Model.Product, Models.Product>
    {
        private readonly IUnitOfWork _unitOfWork;

        public ProductController(IUnitOfWork unitOfWork) :base(unitOfWork)
        {
            //_unitOfWork = unitOfWork ?? throw new ArgumentNullException(nameof(unitOfWork));
        }

        protected override DAL.Model.Product CreateNewEntity()
        {
            return new DAL.Model.Product();
        }

        protected override int GetId(Models.Product model)
        {
            return model.Id;
        }

        //// GET: Product
        //public ActionResult Index()
        //{
        //    return View();
        //}

        //public ActionResult New()
        //{
        //    var viewModel = Mapper.Map<Models.Product>(new DAL.Model.Product());
        //    ViewBag.Title = "New";
        //    return View("Form", viewModel);
        //}

        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //[Authorize(Roles = Models.RoleName.Write)]
        //public ActionResult Save(Models.Product product)
        //{
        //    if (!ModelState.IsValid)
        //    {
        //        ViewBag.Title = "Fix errors";
        //        return View("Form", product);
        //    }

        //    var productRepository = _unitOfWork.GetRepository<DAL.Model.Product>();

        //    if (product.Id == 0)
        //        productRepository.Add(Mapper.Map<DAL.Model.Product>(product));
        //    else
        //    {
        //        productRepository.UpdateSingle(c => c.Id == product.Id, Mapper.Map<DAL.Model.Product>(product));
        //    }

        //    _unitOfWork.Complete();

        //    return RedirectToAction("Index");
        //}

        //public ActionResult Details(int id)
        //{
        //    var productRepository = _unitOfWork.GetRepository<DAL.Model.Product>();
        //    var product = productRepository.SingleOrDefault(c => c.Id == id);

        //    if (product == null)
        //        return HttpNotFound();

        //    ViewBag.Title = "Details";
        //    return View(Mapper.Map<Models.Product>(product));
        //}

        //[Authorize(Roles = Models.RoleName.Write)]
        //public ActionResult Edit(int id)
        //{
        //    var productRepository = _unitOfWork.GetRepository<DAL.Model.Product>();
        //    var product = productRepository.SingleOrDefault(c => c.Id == id);

        //    if (product == null)
        //        return HttpNotFound();

        //    var viewModel = Mapper.Map<Models.Product>(product);

        //    ViewBag.Title = "Edit";

        //    return View("Form", viewModel);
        //}
    }
}

Task 5/WebUI/Controllers/SellerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DAL.UnitOfWork;

namespace WebUI.Controllers
{
    [Authorize(Roles = Models.RoleName.Read)]
    public class SellerController : BaseCRUD<DAL.Model.Seller, Models.Seller>
    {
        public SellerController(IUnitOfWork unitOfWork) : base(unitOfWork)
        {
        }

        protected override DAL.Model.Seller CreateNewEntity()
        {
            return new DAL.Model.Seller();
        }

        protected override int GetId(Models.Seller model)
        {
            return model.Id;
        }
    }
}

Task 5/WebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title – приложение ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    @Html.Partial("_NavBar")
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year – приложение ASP.NET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/lib")
    @RenderSection("scripts", required: false)
</body>
</html>

Task 5/WebUI/Views/Shared/_NavBar.cshtml
<div class="navbar navbar-inverse navbar-fixed-top">
	<div class="container">
		<div class="navbar-header">
			<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
				<span class="icon-bar"></span>
			</button>
			@Html.ActionLink("APP", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
		</div>
		<div class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
                <li>
                    @Html.ActionLink("Домашняя страница", "Index", "Home", new { area = "" }, new { @class = "nav-item navbar-link" })
                </li>
                @if (Request.IsAuthenticated)
                {
                    <li>
                        @Html.ActionLink("Customers", "Index", "Customer", new { area = "" }, new { @class = "nav-item navbar-link" })
                    </li>
                    <li>
                        @Html.ActionLink("Products", "Index", "Product", new { area = "" }, new { @class = "nav-item navbar-link" })
                    </li>
                    <li>
                        @Html.ActionLink("Sellers", "Index", "Seller", new { area = "" }, new { @class = "nav-item navbar-link" })
                    </li>
                    <li>
                        @Html.ActionLink("Orders", "Index", "Order", new { area = "" }, new { @class = "nav-item navbar-link" })
                    </li>
                }
                <li>
                    @Html.ActionLink("О программе", "About", "Home", new { area = "" }, new { @class = "nav-item navbar-link" })
                </li>
                <li>
                    @Html.ActionLink("Контакт", "Contact", "Home", new { area = "" }, new { @class = "nav-item navbar-link" })
                </li>
            </ul>
			@Html.Partial("_LoginPartial")
		</div>
	</div>
</div>